# Introduction

This tutorial will guide you through estimating normal vectors and principal curvatures from 3D point clouds using classic PCA and Jet fitting methods as well as our recent DeepFit method. 


Surface normals and curvatures are a very important properties in shape analysis and are widely used in different fields like computer graphics, computer vision and more. 


### The math
3D point clouds are represented as a matrix of $(x, y, z)$ coordinates of points in 3D space. 
If you are unfamiliar with plane fitting and jets, this section provides a short background. For more in-depth information see the refrences at the bottom. 

The following methods share the following: 
* Input: 3D point cloud  + querry point $q_i$
* Find $q_i$'s k nearest neighbors.  
* Do something fancey :)
* Output: Normal vector at  query point $N_{q_i}$

For estimating the normal at each point we use each point in the point cloud as the query point. 


#### PCA
In this method we estimate the tangent plane to the underlying surface at the query point. This boils down to  solving the eigenvalue and eigenvector decomposition of the covariance matrix created from the points nearest neighbors:

\begin{equation}
C = \frac{1}{k}\sum_{i=1}^{k}(p_i-\hat{p})(p_i-\hat{p})^T
\end{equation}

Here $p_i$ are the neighboring points and $\hat{p}$ is the neighbours centroid. 
The normal vector is the eugenvector associated with the smallest eigenvalue. 

Using this method we cannot directly estimate the principal curvatures (the principal curvatures of a plane are 0).


#### Jet fitting

 An $n$-jet of the height function over a surface is given by:

\begin{equation}
    f(x,y)=J_{\beta,n}(x,y)= \sum_{k=0}^{n}\sum_{j=0}^{k}\beta_{k-j,j}x^{k-j}y^j
\end{equation}

Here $\beta$ is the jet coefficients vector that consists of $N_n=(n+1)(n+2)/2$ terms.

We require that every point satisfy the equation above, yielding the system of linear equations:
\begin{equation}
    M\beta = B
\end{equation}

It is well known that the solution can be expressed in closed-form as: 
\begin{equation}
    \beta = (M^TM)^{-1}M^TB
\end{equation}

Here $M=(1, x_i, y_i, ..., x_i y_i^{n-1}, y_i^n)_{i=1,...,N_p}\in \mathbb{R}^{N_p \times N_n}$ is the Vandermonde matrix and the height function vector $B=(z_1, z_2,...z_{N_p})^T \in \mathbb{R}^N_p$. Both represent the sampled points.


### The code

In [1]:
import sys  
import os
import numpy as np
sys.path.insert(0, '../utils')
sys.path.insert(0, '../models')
sys.path.insert(0, '../trained_models')
import DeepFit
import tutorial_utils as tu
import torch
import ipyvolume as ipv
import ipywidgets as widgets
from IPython.display import display
import functools

gpu_idx = 0
device = torch.device("cpu" if gpu_idx < 0 else "cuda:%d" % 0)

### Generating data
3D point cloud data can be obtained from 3D sensors like LiDAR or RGBD cameras. For this tutorial we will generate a synthetic example. This way we have true ground truth parametric surface as reference for evaluating our results. 

In [ ]:
jet_order_data = 3
n_points = 4096
point_cloud_dataset = tu.SyntheticPointCloudDataset(n_points, jet_order_data, points_per_patch=128)
dataloader = torch.utils.data.DataLoader(point_cloud_dataset, batch_size=256, num_workers=8)

points = point_cloud_dataset.points
gt_normals = point_cloud_dataset.gt_normals

### Normal estimation

In [ ]:
jet_order_fit = 3
for batchind, data in enumerate(dataloader):
    points, scale_radius = data[0], data[1]
    points = points.to(device)
    scale_radius = scale_radius.to(device)
    
    # compute jet coefficients and normal estimation
    pca_beta, n_est, _ = DeepFit.fit_Wjet(points, torch.ones_like(points[:, 0]), order=1,
                               compute_neighbor_normals=False)
    pca_normals = n_est if batchind==0 else torch.cat([pca_normals, n_est], 0)
    
    jet_beta, n_est, _ = DeepFit.fit_Wjet(points, torch.ones_like(points[:, 0]), order=jet_order_fit,
                               compute_neighbor_normals=False)
    jet_normals = n_est if batchind==0 else torch.cat([jet_normals, n_est], 0)
    
    # compute principal curvatures
    jet_curv_est, principal_dirs = tu.compute_principal_curvatures(jet_beta)
    jet_curv_est = jet_curv_est / scale_radius.unsqueeze(-1).repeat(1, jet_curv_est.shape[1])
    jet_curv_est = jet_curv_est.detach().cpu()
    jet_curvatures = jet_curv_est if batchind==0 else torch.cat([jet_curvatures, jet_curv_est], 0)

The normals are unoriented so we will now flip them upwards (assuming that the positive z axis points up)

In [ ]:
n_sign = torch.sign(torch.sum(pca_normals*
                              torch.tensor([0., 0., 1.], device=pca_normals.device).repeat([n_points, 1]), dim=1)).unsqueeze(-1)
pca_normals = n_sign * pca_normals
pca_normals = pca_normals.detach().cpu().numpy()

n_sign = torch.sign(torch.sum(jet_normals*
                              torch.tensor([0., 0., 1.], device=jet_normals.device).repeat([n_points, 1]), dim=1)).unsqueeze(-1)
jet_normals = n_sign * jet_normals
jet_normals = jet_normals.detach().cpu().numpy()

### Visualization

In [ ]:
color_n_pca = tu.normal2rgb(pca_normals) #convert normal vectors to RGB
color_n_jet = tu.normal2rgb(jet_normals)
color_n_gt = tu.normal2rgb(gt_normals)

curvature_range_min = [-torch.mean(torch.abs(jet_curvatures[:, 1])) - torch.std(torch.abs(jet_curvatures[:, 1])), 
                                torch.mean(torch.abs(jet_curvatures[:, 1])) + torch.std(torch.abs(jet_curvatures[:, 1]))]
curvature_range_max = [-torch.mean(torch.abs(jet_curvatures[:, 0])) - torch.std(torch.abs(jet_curvatures[:, 0])), 
                                torch.mean(np.abs(jet_curvatures[:, 0])) + torch.std(torch.abs(jet_curvatures[:, 0]))]                                   
color_curv = tu.curvatures2rgb(jet_curvatures.clone(),  k1_range=curvature_range_max, k2_range=curvature_range_min)

# make some buttons to toggle between the colors 
btn_pca = widgets.Button(description='PCA')
btn_pca.style.button_color='lightgray'
btn_jet = widgets.Button(description='Jet')
btn_jet.style.button_color='lightgray'
btn_solid = widgets.Button(description='solid')
btn_solid.style.button_color='lightgray'
btn_gt = widgets.Button(description='GT')
btn_gt.style.button_color='lightgray'
btn_curv = widgets.Button(description='curvature')
btn_curv.style.button_color='lightgray'

def update_pc_normal_color(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    if b.description == 'PCA':
        scatter_h.color = color_n_pca
    elif b.description == 'Jet': 
        scatter_h.color = color_n_jet
    elif b.description == 'solid':
        scatter_h.color = 'red'
    elif b.description == 'GT':
        scatter_h.color = color_n_gt
    elif b.description == 'curvature':
        scatter_h.color = color_curv


#plot
fig_h = ipv.figure()
scatter_h = ipv.pylab.scatter(point_cloud_dataset.points[:, 0], 
                              point_cloud_dataset.points[:, 1], 
                              point_cloud_dataset.points[:, 2], size=1, marker="sphere", color='red')
ipv.pylab.xyzlim(-1, 1)
ipv.style.use('minimal')
# button function 
btn_pca.on_click(functools.partial(update_pc_normal_color, scatter_h=scatter_h))
btn_jet.on_click(functools.partial(update_pc_normal_color, scatter_h=scatter_h))
btn_gt.on_click(functools.partial(update_pc_normal_color, scatter_h=scatter_h))
btn_solid.on_click(functools.partial(update_pc_normal_color, scatter_h=scatter_h))
btn_curv.on_click(functools.partial(update_pc_normal_color, scatter_h=scatter_h))

display(widgets.VBox((widgets.HBox((btn_pca, btn_jet, btn_gt, btn_solid, btn_curv)), fig_h)))

### Loading the data

In [8]:
point_cloud_dataset = tu.SinglePointCloudDataset('./Boxy_smooth100k.xyz', points_per_patch=256)
print(point_cloud_dataset.points)


[[-0.47420675  0.04765987 -0.40615332]
 [-0.19475208  0.22290343  0.47209102]
 [-0.54465634 -0.18347211  0.03932041]
 ...
 [-0.13093506  0.3629976  -0.06708436]
 [ 0.5013776   0.18889578  0.12530105]
 [-0.12950778  0.3153689  -0.2243162 ]]


### Fit an n-jet (and compute normal vector)
This may take a while, depending on the number of points. 

Note: this is the classic jet fitting method which uses non-weighted least squares. 

In [9]:
jet_order =3
dataloader = torch.utils.data.DataLoader(point_cloud_dataset, batch_size=256, num_workers=8)

for batchind, data in enumerate(dataloader, 0):
    points = data[0]
    data_trans = data[1]
    scale_radius = data[-1]
    points = points.to(device)
    data_trans = data_trans.to(device)
    scale_radius = scale_radius.to(device)
    
    beta, n_est, neighbors_n_est = DeepFit.fit_Wjet(points, torch.ones_like(points[:, 0]), order=jet_order,
                               compute_neighbor_normals=False)
    n_est = torch.bmm(n_est.unsqueeze(1), data_trans.transpose(2, 1)).squeeze(dim=1) # cancel out pca
    n_est = n_est.detach().cpu()
    normals = n_est if batchind==0 else torch.cat([normals, n_est], 0)
    
    curv_est, principal_dirs = tu.compute_principal_curvatures(beta)
    curv_est = curv_est / scale_radius.unsqueeze(-1).repeat(1, curv_est.shape[1])
    curv_est = curv_est.detach().cpu()
    curvatures = curv_est if batchind == 0 else torch.cat([curvatures, curv_est], 0)


The normals are unoriented so we will now flip them outwards (assuming that the origin is an internal point and the shape is simple)

In [10]:
n_sign = torch.sign(torch.sum(normals*torch.tensor(point_cloud_dataset.points), dim=1)).unsqueeze(-1)
normals = n_sign * normals
normals = normals.detach().cpu()
curvatures = n_sign.repeat([1, 2]) * curvatures

### Visualize the point cloud
We plot the point cloud and allow for 3 color overlays:
* Solid - (all points have the same color)
* Normals - We map the normal vectors to the RGB cube and use these values for coloring the point cloud.
* Curvatures - We map the principal curvatures to the XXX colormap to RGB. 

In [11]:
color_n = tu.normal2rgb(normals.numpy()) #convert normal vectors to RGB
curvature_range_min = [-torch.mean(torch.abs(curvatures[:, 1])) - torch.std(torch.abs(curvatures[:, 1])), 
                                torch.mean(torch.abs(curvatures[:, 1])) + torch.std(torch.abs(curvatures[:, 1]))]
curvature_range_max = [-torch.mean(torch.abs(curvatures[:, 0])) - torch.std(torch.abs(curvatures[:, 0])), 
                                torch.mean(np.abs(curvatures[:, 0])) + torch.std(torch.abs(curvatures[:, 0]))]                                   
color_curv = tu.curvatures2rgb(curvatures.clone(),  k1_range=curvature_range_max, k2_range=curvature_range_min)

# make some buttons to toggle between the colors 
btn_pc = widgets.Button(description='Solid')
btn_pc.style.button_color='lightgray'
btn_n = widgets.Button(description='normals')
btn_n.style.button_color='lightgray'
btn_c = widgets.Button(description='Curvatures')
btn_c.style.button_color='lightgray'

def update_pc_color_to_solid(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = 'red'

    
def update_pc_color_to_normal(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = color_n
    
def update_pc_color_to_curv(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = color_curv

#plot
fig_h = ipv.figure()
scatter_h = ipv.pylab.scatter(point_cloud_dataset.points[:, 0], 
                              point_cloud_dataset.points[:, 1], 
                              point_cloud_dataset.points[:, 2], size=0.5, marker="sphere", color='red')
ipv.pylab.xyzlim(-1, 1)
ipv.style.use('minimal')
# ipv.show()

btn_pc.on_click(functools.partial(update_pc_color_to_solid, scatter_h=scatter_h))
btn_n.on_click(functools.partial(update_pc_color_to_normal, scatter_h=scatter_h))
btn_c.on_click(functools.partial(update_pc_color_to_curv, scatter_h=scatter_h))
display(widgets.VBox((widgets.HBox((btn_pc, btn_n, btn_c)), fig_h)))

### Fit an n-jet using DeepFit (and compute normal vector and principal curvatures)
We first load the pretrained model and its parameters. 

In [12]:
trained_model_path = '../trained_models/DeepFit'
params = torch.load(os.path.join(trained_model_path, 'DeepFit_params.pth'))
k_neighbors = params.points_per_patch #note you can use a different number, this is what the network trained on
jet_order = params.jet_order
print('Using {} order jet for surface fitting'.format(jet_order))
model = DeepFit.DeepFit(k=1, num_points=k_neighbors, use_point_stn=params.use_point_stn,
                        use_feat_stn=params.use_feat_stn, point_tuple=params.point_tuple, sym_op=params.sym_op,
                        arch=params.arch, n_gaussians=params.n_gaussians, jet_order=jet_order,
                        weight_mode=params.weight_mode, use_consistency=False)
checkpoint = torch.load(os.path.join(trained_model_path, 'DeepFit.pth'))
model.load_state_dict(checkpoint)
model.to(device)

Using 3 order jet for surface fitting


DeepFit(
  (feat): PointNetEncoder(
    (pointfeat): PointNetFeatures(
      (conv1): Conv1d(3, 64, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (stn1): QSTN(
        (conv1): Conv1d(3, 64, kernel_size=(1,), stride=(1,))
        (conv2): Conv1d(64, 128, kernel_size=(1,), stride=(1,))
        (conv3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
        (mp1): MaxPool1d(kernel_size=256, stride=256, padding=0, dilation=1, ceil_mode=False)
        (fc1): Linear(in_features=1024, out_features=512, bias=True)
        (fc2): Linear(in_features=512, out_features=256, bias=True)
        (fc3): Linear(in_features=256, out_features=4, bias=True)
        (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (bn2): Bat

Next we use DeepFit to fit a surface at each point in the point cloud. 
This may take a while, depending on the number of points. 

In [16]:
dataloader = torch.utils.data.DataLoader(point_cloud_dataset, batch_size=128, num_workers=8)

for batchind, data in enumerate(dataloader, 0):
    points = data[0]
    data_trans = data[1]
    scale_radius = data[-1].squeeze()
    points = points.to(device)
    data_trans = data_trans.to(device)
    scale_radius = scale_radius.to(device)
    n_est, beta, weights, trans, trans2, neighbors_n_est = model.forward(points)
    if params.use_point_stn:
        n_est = torch.bmm(n_est.unsqueeze(1), trans.transpose(2, 1)).squeeze(dim=1) # cancel out poitnnet stn
    n_est = torch.bmm(n_est.unsqueeze(1), data_trans.transpose(2, 1)).squeeze(dim=1)  # cancel out pca
    n_est = n_est.detach().cpu()
    normals = n_est if batchind == 0 else torch.cat([normals, n_est], 0)
    
    curv_est, principal_dirs = tu.compute_principal_curvatures(beta)
    curv_est = curv_est / scale_radius.unsqueeze(-1).repeat(1, curv_est.shape[1])
    curv_est = curv_est.detach().cpu()
    curvatures = curv_est if batchind == 0 else torch.cat([curvatures, curv_est], 0)
    

The normals are unoriented so we will now flip them outwards (assuming that the origin is an internal point and the shape is simple)

In [17]:
n_sign = torch.sign(torch.sum(normals*torch.tensor(point_cloud_dataset.points), dim=1)).unsqueeze(-1)
normals = n_sign * normals
normals = normals.detach().cpu()
curvatures = n_sign.repeat([1, 2]) * curvatures

### Visualize the point cloud
We plot the point cloud and allow for 3 color overlays:
* Solid - (all points have the same color)
* Normals - We map the normal vectors to the RGB cube and use these values for coloring the point cloud.
* Curvatures - We map the principal curvatures to the XXX colormap to RGB. 

In [18]:
color_n = tu.normal2rgb(normals.numpy()) #convert normal vectors to RGB
curvature_range_min = [-torch.mean(torch.abs(curvatures[:, 1])) - torch.std(torch.abs(curvatures[:, 1])), 
                                torch.mean(torch.abs(curvatures[:, 1])) + torch.std(torch.abs(curvatures[:, 1]))]
curvature_range_max = [-torch.mean(torch.abs(curvatures[:, 0])) - torch.std(torch.abs(curvatures[:, 0])), 
                                torch.mean(np.abs(curvatures[:, 0])) + torch.std(torch.abs(curvatures[:, 0]))]                                   
color_curv = tu.curvatures2rgb(curvatures.clone(),  k1_range=curvature_range_max, k2_range=curvature_range_min)

# make some buttons to toggle between the colors 
btn_pc = widgets.Button(description='Solid')
btn_pc.style.button_color='lightgray'
btn_n = widgets.Button(description='normals')
btn_n.style.button_color='lightgray'
btn_c = widgets.Button(description='Curvatures')
btn_c.style.button_color='lightgray'

def update_pc_color_to_solid(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = 'red'

    
def update_pc_color_to_normal(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = color_n

def update_pc_color_to_curv(b, scatter_h):
    """    
        this function is linked to the buttons and updates the the point cloud color
    """
    scatter_h.color = color_curv

#plot
fig_h = ipv.figure()
scatter_h = ipv.pylab.scatter(point_cloud_dataset.points[:, 0], 
                              point_cloud_dataset.points[:, 1], 
                              point_cloud_dataset.points[:, 2], size=0.5, marker="sphere", color='red')
ipv.pylab.xyzlim(-1, 1)
ipv.style.use('minimal')
# ipv.show()

btn_pc.on_click(functools.partial(update_pc_color_to_solid, scatter_h=scatter_h))
btn_n.on_click(functools.partial(update_pc_color_to_normal, scatter_h=scatter_h))
btn_c.on_click(functools.partial(update_pc_color_to_curv, scatter_h=scatter_h))
display(widgets.VBox((widgets.HBox((btn_pc, btn_n, btn_c)), fig_h)))

### References
* [PCL normal estimation using PCA](http://pointclouds.org/documentation/tutorials/normal_estimation.php)
* [CGAL normal estimation using Jets](https://doc.cgal.org/latest/Jet_fitting_3/index.html#Jet_fitting_3Mathematical)
* [DeepFit paper](https://arxiv.org/pdf/2003.10826.pdf)
* [Jet fitting paper](https://graphics.stanford.edu/courses/cs468-03-fall/Papers/cazals_jets.pdf)